// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56LWkz_nrs3bqCeQ_GH3XBZojPy_1iHk',
    appId: '1:212870032924:web:81aa3bd864d96cc42eb9d9',
    messagingSenderId: '212870032924',
    projectId: 'cdrotas',
    authDomain: 'cdrotas.firebaseapp.com',
    storageBucket: 'cdrotas.appspot.com',
    measurementId: 'G-YHSY5KDW5D',
    databaseURL: 'cdrotas-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0VSCFhv6-bx__wgfNvnfNqRD5XQwP-8g',
    appId: '1:212870032924:android:8a05d775a6bc09de2eb9d9',
    messagingSenderId: '212870032924',
    projectId: 'cdrotas',
    storageBucket: 'cdrotas.appspot.com',
    databaseURL: 'cdrotas-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FWT0_ercMUau6dtwZPBzNlvo0px8a0c',
    appId: '1:212870032924:ios:91f9aa97e2ad42782eb9d9',
    messagingSenderId: '212870032924',
    projectId: 'cdrotas',
    storageBucket: 'cdrotas.appspot.com',
    iosClientId:
        '212870032924-93i6jb1lpplmjfdvhibi36kkau985qju.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuapp',
    databaseURL: 'cdrotas-default-rtdb.firebaseio.com',
  );
}
